syntax = "proto3";

package cf3d.v1;

import "google/protobuf/timestamp.proto";

/** Enums **/

enum TaskStatus {
  TASK_STATUS_UNSPECIFIED = 0;
  TASK_STATUS_PENDING = 1;
  TASK_STATUS_RUNNING = 2;
  TASK_STATUS_SUCCEEDED = 3;
  TASK_STATUS_FAILED = 4;
}

/** Events **/

message TaskStatusUpdate {
  string task_id = 1;
  TaskStatus status = 2;
}

/** Queries */

message ListTasksRequest {
  string job_id = 1;
}

message TaskDetails {
  string id = 1;
  string job_id = 2;
  int32 frame_number = 3;
  optional google.protobuf.Timestamp created_at = 4;
  optional google.protobuf.Timestamp started_at = 5;
  optional google.protobuf.Timestamp queued_at = 6;
  optional google.protobuf.Timestamp completed_at = 7;
  string status = 8;
  int32 retry_count = 9;
}

message ListTasksResponse {
  repeated TaskDetails tasks = 1;
}

/** Mutations **/

message RetryAllFailedTasksRequest {
  string job_id = 1;
}

message RetryFailedTaskRequest {
  string task_id = 1;
}
